name: LibsDisguiseWGFlags
main: nl.chimpgamer.libsdisguiseswgflags.LibsDisguisesWGFlagsPlugin
version: ${version}
authors:
  - ChimpGamer
api-version: 1.13

depend:
  - LibsDisguises
  - WorldGuard

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.20